"""Native gMAS Studio graph import/export codecs.

GraphSpec JSON is the lossless portable artifact. Generated Python is clean,
code-first GraphBuilder source and is imported back by statically parsing a
safe literal subset of builder calls; user Python is never executed.
"""

import ast
from datetime import UTC, datetime
import json
from pprint import pformat
import re
from typing import Any

from backend.models.graph import GraphExportResponse, GraphSaveRequest

GRAPH_SPEC_FORMAT = "gmas.studio.graph"
GRAPH_SPEC_VERSION = "1.0"
_RESPONSE_ONLY_FIELDS = {"graph_id", "created_at", "updated_at", "validation_errors"}
_SECRET_KEYS = {"api_key", "apikey", "access_token", "refresh_token", "token", "password", "secret", "authorization"}
_PYTHON_RUNTIME_LIMITED_LLM_KEYS = {"top_k", "tool_calling_enabled", "tool_choice", "parallel_tool_calls", "extra_params"}


def export_graph_json(
    graph: GraphSaveRequest | dict[str, Any],
    *,
    source_graph_id: str | None = None,
    filename_hint: str | None = None,
) -> GraphExportResponse:
    """Export a graph as a native versioned GraphSpec JSON document."""
    graph_req = normalize_graph_payload(graph)
    spec = make_graph_spec(graph_req, source_graph_id=source_graph_id)
    content = json.dumps(spec, ensure_ascii=False, indent=2)
    return GraphExportResponse(
        format="gmas_json",
        filename=f"{_filename_slug(filename_hint or graph_req.name)}.gmas.json",
        mime_type="application/json",
        content=content,
        warnings=[],
    )


def export_graph_python(
    graph: GraphSaveRequest | dict[str, Any],
    *,
    source_graph_id: str | None = None,
    filename_hint: str | None = None,
) -> GraphExportResponse:
    """Export a graph as clean, human-editable GraphBuilder Python code."""
    graph_req = normalize_graph_payload(graph)
    spec = make_graph_spec(graph_req, source_graph_id=source_graph_id)
    content = _render_python_builder_export(spec)
    warnings = _python_export_warnings(spec)
    return GraphExportResponse(
        format="gmas_python",
        filename=f"{_filename_slug(filename_hint or graph_req.name)}.gmas.py",
        mime_type="text/x-python",
        content=content,
        warnings=warnings,
    )


def import_gmas_json(
    payload: Any,
    *,
    name_override: str | None = None,
) -> tuple[GraphSaveRequest, list[str]]:
    """Import a native GraphSpec JSON document or a raw GraphSaveRequest body."""
    graph = normalize_graph_payload(payload, name_override=name_override)
    return graph, []


def import_gmas_python(
    source_text: Any,
    *,
    name_override: str | None = None,
) -> tuple[GraphSaveRequest, list[str]]:
    """Import GraphBuilder Python by statically reading literal builder calls.

    This intentionally does not execute source code. Import supports the clean
    SDK format generated by gMAS Studio plus hand-written equivalents using
    literal GraphBuilder calls.
    """
    if not isinstance(source_text, str) or not source_text.strip():
        raise ValueError("Python import payload is empty.")

    try:
        tree = ast.parse(source_text)
    except SyntaxError as exc:
        raise ValueError(f"Python import payload has invalid syntax: {exc.msg}") from exc

    return _import_graph_builder_python(tree, name_override=name_override)


def _import_graph_builder_python(
    tree: ast.Module,
    *,
    name_override: str | None = None,
) -> tuple[GraphSaveRequest, list[str]]:
    """Import a safe subset of hand-written/generated GraphBuilder Python.

    The importer does not execute Python. It statically reads literal constants
    and calls such as ``builder.add_agent(...)`` / ``builder.add_workflow_edge(...)``.
    """
    constants: dict[str, Any] = {}
    builder_names: set[str] = set()
    agents: list[dict[str, Any]] = []
    parsed_edges: list[dict[str, Any]] = []
    start_node: str | None = None
    end_node: str | None = None
    task_query = ""
    task_targets: list[str] = []

    for node in tree.body:
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name):
                    if _is_call_named(node.value, "GraphBuilder"):
                        builder_names.add(target.id)
                    else:
                        try:
                            constants[target.id] = _literal_from_ast(node.value, constants)
                        except ValueError:
                            pass
        elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            try:
                constants[node.target.id] = _literal_from_ast(node.value, constants) if node.value else None
            except ValueError:
                pass

    for node in tree.body:
        call = node.value if isinstance(node, ast.Expr) and isinstance(node.value, ast.Call) else None
        if call is None or not isinstance(call.func, ast.Attribute):
            continue
        owner = call.func.value
        if not isinstance(owner, ast.Name) or (builder_names and owner.id not in builder_names):
            continue

        method = call.func.attr
        args = [_literal_from_ast(arg, constants) for arg in call.args]
        kwargs = {
            kw.arg: _literal_from_ast(kw.value, constants)
            for kw in call.keywords
            if kw.arg is not None
        }

        if method == "add_agent":
            agents.append(_agent_from_builder_call(args, kwargs))
        elif method in {"add_workflow_edge", "add_conditional_edge"}:
            parsed_edges.append(_edge_from_builder_call(method, args, kwargs))
        elif method == "set_start_node":
            start_node = str(args[0] if args else kwargs.get("node_id") or "") or None
        elif method == "set_end_node":
            end_node = str(args[0] if args else kwargs.get("node_id") or "") or None
        elif method == "add_task":
            task_query = str(kwargs.get("query") or (args[1] if len(args) > 1 else args[0] if args else "") or "")
        elif method == "connect_task_to_agents":
            raw_targets = kwargs.get("agent_ids")
            if raw_targets is None and len(args) > 1:
                raw_targets = args[1]
            if isinstance(raw_targets, list):
                task_targets = [str(item) for item in raw_targets]

    studio = constants.get("STUDIO") if isinstance(constants.get("STUDIO"), dict) else {}
    graph_data = {
        "name": name_override or constants.get("GRAPH_NAME") or "Imported Python SDK Graph",
        "description": constants.get("GRAPH_DESCRIPTION") or "",
        "agents": agents,
        "edges": studio.get("edges") if isinstance(studio.get("edges"), list) else parsed_edges,
        "positions": studio.get("positions") if isinstance(studio.get("positions"), dict) else constants.get("POSITIONS", {}),
        "start_node": start_node,
        "end_node": end_node,
        "task_targets": task_targets or constants.get("TASK_TARGETS", []),
        "task_query": task_query or constants.get("TASK_QUERY", ""),
        "llm_provider_id": studio.get("llm_provider_id") or constants.get("LLM_PROVIDER_ID"),
        "llm_model": studio.get("llm_model") or constants.get("LLM_MODEL"),
        "run_config": studio.get("run_config") if isinstance(studio.get("run_config"), dict) else constants.get("RUN_CONFIG", {}),
    }
    if not graph_data["agents"]:
        raise ValueError("Python import needs literal GraphBuilder add_agent(...) calls.")
    return normalize_graph_payload(graph_data), []


def _literal_from_ast(node: ast.AST, constants: dict[str, Any]) -> Any:
    if isinstance(node, ast.Name) and node.id in constants:
        return constants[node.id]
    if isinstance(node, ast.Call) and _is_call_named(node, "LLMConfig"):
        return {kw.arg: _literal_from_ast(kw.value, constants) for kw in node.keywords if kw.arg is not None}
    try:
        return ast.literal_eval(node)
    except Exception as exc:
        raise ValueError(f"Unsupported non-literal Python export value: {ast.dump(node, include_attributes=False)}") from exc


def _is_call_named(node: ast.AST, name: str) -> bool:
    if not isinstance(node, ast.Call):
        return False
    func = node.func
    return (isinstance(func, ast.Name) and func.id == name) or (isinstance(func, ast.Attribute) and func.attr == name)


def _agent_from_builder_call(args: list[Any], kwargs: dict[str, Any]) -> dict[str, Any]:
    positional_names = [
        "agent_id", "display_name", "persona", "description", "embedding", "trust_score",
        "llm_config", "tools", "input_schema", "output_schema", "llm_backbone", "base_url",
        "api_key", "max_tokens", "temperature", "timeout", "top_p", "stop_sequences",
    ]
    merged = dict(kwargs)
    for key, value in zip(positional_names, args, strict=False):
        merged.setdefault(key, value)

    agent_id = merged.pop("agent_id", None)
    if not agent_id:
        raise ValueError("builder.add_agent(...) requires a literal agent_id.")
    llm_config = merged.pop("llm_config", None) or {}
    if not isinstance(llm_config, dict):
        llm_config = {}
    direct_llm_keys = {
        "model_name", "base_url", "api_key", "max_tokens", "temperature", "timeout", "top_p",
        "top_k", "stop_sequences", "tool_calling_enabled", "tool_choice", "parallel_tool_calls", "extra_params",
    }
    for key in list(merged):
        if key in direct_llm_keys:
            llm_config[key] = merged.pop(key)
    llm_backbone = merged.pop("llm_backbone", None)
    if llm_backbone and "model_name" not in llm_config:
        llm_config["model_name"] = llm_backbone
    return {
        "agent_id": str(agent_id),
        "display_name": merged.pop("display_name", None) or str(agent_id),
        "persona": merged.pop("persona", "") or "",
        "description": merged.pop("description", "") or "",
        "llm_backbone": llm_backbone,
        "llm_config": llm_config or None,
        "tools": merged.pop("tools", []) or [],
        "input_schema": merged.pop("input_schema", None),
        "output_schema": merged.pop("output_schema", None),
    }


def _edge_from_builder_call(method: str, args: list[Any], kwargs: dict[str, Any]) -> dict[str, Any]:
    source = kwargs.get("source") or (args[0] if args else None)
    target = kwargs.get("target") or (args[1] if len(args) > 1 else None)
    if not source or not target:
        raise ValueError(f"builder.{method}(...) requires literal source and target.")
    edge: dict[str, Any] = {
        "source": str(source),
        "target": str(target),
        "weight": kwargs.get("weight", 1.0),
        "enabled": True,
    }
    if method == "add_conditional_edge":
        condition = kwargs.get("condition") or (args[2] if len(args) > 2 else None)
        edge.update(_ui_condition_from_builder_condition(condition))
    return edge


def _ui_condition_from_builder_condition(condition: Any) -> dict[str, Any]:
    if condition in (None, "", "always"):
        return {}
    if condition == "never":
        return {"condition": "skip"}
    if condition in {"source_success", "source_failed"}:
        return {"condition": condition}
    if isinstance(condition, str) and condition.startswith("contains:"):
        return {"condition": "conditional", "label": condition.removeprefix("contains:")}
    return {"condition": str(condition)}


def make_graph_spec(
    graph: GraphSaveRequest | dict[str, Any],
    *,
    source_graph_id: str | None = None,
) -> dict[str, Any]:
    """Create a versioned portable GraphSpec envelope from a graph request."""
    graph_req = normalize_graph_payload(graph)
    metadata: dict[str, Any] = {
        "exported_from": "gmas-demo",
        "exported_at": datetime.now(UTC).isoformat(),
    }
    if source_graph_id:
        metadata["source_graph_id"] = source_graph_id
    return {
        "format": GRAPH_SPEC_FORMAT,
        "version": GRAPH_SPEC_VERSION,
        "graph": graph_req.model_dump(mode="json"),
        "metadata": metadata,
    }


def normalize_graph_payload(
    payload: GraphSaveRequest | dict[str, Any] | str,
    *,
    name_override: str | None = None,
) -> GraphSaveRequest:
    """Coerce raw graph/envelope input into a sanitized GraphSaveRequest."""
    if isinstance(payload, GraphSaveRequest):
        raw: Any = payload.model_dump(mode="json")
    elif isinstance(payload, str):
        text = payload.strip()
        if not text:
            raise ValueError("Graph import payload is empty.")
        try:
            raw = json.loads(text)
        except json.JSONDecodeError as exc:
            raise ValueError(f"Graph import payload is not valid JSON: {exc.msg}") from exc
    else:
        raw = payload

    if not isinstance(raw, dict):
        raise ValueError("Graph import payload must be a JSON object.")

    if raw.get("format") == GRAPH_SPEC_FORMAT:
        version = raw.get("version")
        if version != GRAPH_SPEC_VERSION:
            raise ValueError(f"Unsupported gMAS GraphSpec version: {version!r}")
        graph_data = raw.get("graph")
    elif "graph" in raw and isinstance(raw.get("graph"), dict) and raw.get("format") in {None, GRAPH_SPEC_FORMAT}:
        # Be permissive for future callers that omit the format marker but keep an envelope.
        graph_data = raw.get("graph")
    else:
        graph_data = raw

    if not isinstance(graph_data, dict):
        raise ValueError("GraphSpec graph payload must be a JSON object.")

    sanitized = _sanitize_graph_data(graph_data)
    if name_override and name_override.strip():
        sanitized["name"] = name_override.strip()
    try:
        return GraphSaveRequest(**sanitized)
    except Exception as exc:
        raise ValueError(f"GraphSpec does not match GraphSaveRequest: {exc}") from exc


def _sanitize_graph_data(graph_data: dict[str, Any]) -> dict[str, Any]:
    cleaned = {k: v for k, v in graph_data.items() if k not in _RESPONSE_ONLY_FIELDS}
    return _sanitize_export_value(cleaned)


def _sanitize_export_value(value: Any, key: str | None = None) -> Any:
    if key is not None and _is_secret_key(key):
        return None
    if isinstance(value, dict):
        return {k: _sanitize_export_value(v, k) for k, v in value.items()}
    if isinstance(value, list):
        return [_sanitize_export_value(item) for item in value]
    return value


def _is_secret_key(key: str) -> bool:
    normalized = re.sub(r"[^a-z0-9]+", "_", key.lower()).strip("_")
    return normalized in _SECRET_KEYS or normalized.endswith("_secret") or normalized.endswith("_token")


def _python_export_warnings(spec: dict[str, Any]) -> list[str]:
    graph = spec.get("graph") if isinstance(spec.get("graph"), dict) else {}
    runtime_limited_keys: set[str] = set()
    for agent in graph.get("agents", []) or []:
        if not isinstance(agent, dict):
            continue
        llm = agent.get("llm_config")
        if not isinstance(llm, dict):
            continue
        for key in _PYTHON_RUNTIME_LIMITED_LLM_KEYS:
            if llm.get(key) not in (None, [], {}):
                runtime_limited_keys.add(key)
    if not runtime_limited_keys:
        return []
    fields = ", ".join(sorted(runtime_limited_keys))
    return [
        "GraphBuilder runtime does not preserve these extended LLM fields in executable Python: "
        f"{fields}. GraphSpec JSON and Studio Python import still preserve them."
    ]


def _filename_slug(value: str | None) -> str:
    slug = re.sub(r"[^A-Za-z0-9._-]+", "-", (value or "graph").strip()).strip("-._")
    return slug[:80] or "graph"


def _render_python_builder_export(spec: dict[str, Any]) -> str:
    graph = spec["graph"]
    lines = [
        '"""Generated by gMAS Studio.',
        '',
        'This is code-first GraphBuilder Python: edit the builder.add_agent /',
        'builder.add_*_edge calls directly. GraphSpec JSON remains the canonical',
        'lossless artifact for visual round-trip exports.',
        '"""',
        '',
        'from gmas.builder import GraphBuilder',
    ]
    if any((agent.get("llm_config") or {}) for agent in graph.get("agents", [])):
        lines.append('from gmas.core.schema import LLMConfig')
    lines.extend(['', f'GRAPH_NAME = {_py_literal(graph.get("name") or "gMAS Graph")}', f'GRAPH_DESCRIPTION = {_py_literal(graph.get("description") or "")}', f'TASK_QUERY = {_py_literal(graph.get("task_query") or "")}', f'TASK_TARGETS = {_py_literal(graph.get("task_targets") or [])}', '', 'builder = GraphBuilder()', ''])

    for agent in graph.get("agents", []):
        lines.extend(_render_builder_agent(agent))
        lines.append('')
    for edge in graph.get("edges", []):
        rendered = _render_builder_edge(edge)
        if rendered:
            lines.append(rendered)
    if graph.get("edges"):
        lines.append('')
    if graph.get("start_node"):
        lines.append(f'builder.set_start_node({_py_literal(graph["start_node"])})')
    if graph.get("end_node"):
        lines.append(f'builder.set_end_node({_py_literal(graph["end_node"])})')
    if graph.get("task_query"):
        lines.extend(['', 'builder.add_task(query=TASK_QUERY)'])
        if graph.get("task_targets"):
            lines.append('builder.connect_task_to_agents(agent_ids=TASK_TARGETS, bidirectional=True)')
        else:
            lines.append('builder.connect_task_to_agents(bidirectional=True)')
    studio = {
        "positions": graph.get("positions") or {},
        "edges": graph.get("edges") or [],
        "run_config": graph.get("run_config") or {},
        "llm_provider_id": graph.get("llm_provider_id"),
        "llm_model": graph.get("llm_model"),
    }
    lines.extend(['', 'graph = builder.build()', '', '# Studio-only metadata: layout, disabled edges, and run settings.', f'STUDIO = {_py_literal(studio)}', ''])
    return "\n".join(lines)


def _render_builder_agent(agent: dict[str, Any]) -> list[str]:
    kwargs: list[tuple[str, Any]] = [
        ("agent_id", agent["agent_id"]),
        ("display_name", agent.get("display_name") or agent["agent_id"]),
        ("persona", agent.get("persona") or ""),
        ("description", agent.get("description") or ""),
    ]
    llm = agent.get("llm_config") or {}
    if agent.get("llm_backbone"):
        kwargs.append(("llm_backbone", agent.get("llm_backbone")))
    llm_config_fields = {
        key: llm[key]
        for key in ("model_name", "base_url", "api_key", "max_tokens", "temperature", "timeout", "top_p", "stop_sequences")
        if llm.get(key) not in (None, [], {})
    }
    if llm_config_fields:
        kwargs.append(("llm_config", _LLMConfigLiteral(llm_config_fields)))
    for key in ("tools", "input_schema", "output_schema"):
        value = agent.get(key)
        if value not in (None, [], {}):
            kwargs.append((key, value))
    for key in ("top_k", "tool_calling_enabled", "tool_choice", "parallel_tool_calls", "extra_params"):
        if llm.get(key) not in (None, [], {}):
            kwargs.append((key, llm[key]))
    return _render_call("builder.add_agent", kwargs)


def _render_builder_edge(edge: dict[str, Any]) -> str | None:
    if edge.get("enabled") is False:
        return f'# Disabled in Studio: {edge.get("source")} -> {edge.get("target")}'
    try:
        weight = float(edge.get("weight", 1.0))
    except (TypeError, ValueError):
        weight = 1.0
    if weight <= 0:
        return f'# Zero-weight edge skipped in runtime: {edge.get("source")} -> {edge.get("target")}'
    condition = _builder_condition(edge)
    if condition:
        return f'builder.add_conditional_edge({_py_literal(edge["source"])}, {_py_literal(edge["target"])}, condition={_py_literal(condition)}, weight={_py_literal(weight)})'
    return f'builder.add_workflow_edge({_py_literal(edge["source"])}, {_py_literal(edge["target"])}, weight={_py_literal(weight)})'


def _builder_condition(edge: dict[str, Any]) -> str | None:
    condition = edge.get("condition")
    label = (edge.get("label") or "").strip()
    if not condition or condition in {"always", ""}:
        return None
    if condition in {"source_success", "source_failed"}:
        return condition
    if condition == "conditional":
        return f"contains:{label}" if label else None
    if condition == "skip":
        return "never"
    if condition == "loop":
        return f"contains:{label}" if label else "always"
    return str(condition)


def _render_call(name: str, kwargs: list[tuple[str, Any]]) -> list[str]:
    lines = [f'{name}(']
    for key, value in kwargs:
        rendered = _py_literal(value)
        if "\n" in rendered:
            rendered = rendered.replace("\n", "\n    ")
        lines.append(f'    {key}={rendered},')
    lines.append(')')
    return lines


class _LLMConfigLiteral(dict):
    pass


def _py_literal(value: Any) -> str:
    if isinstance(value, _LLMConfigLiteral):
        inner = []
        for key, item in value.items():
            if item not in (None, [], {}):
                inner.append(f'    {key}={_py_literal(item)},')
        return 'LLMConfig(\n' + '\n'.join(inner) + '\n)'
    return pformat(value, width=100, sort_dicts=False)
